/*
 * Nuva OS - Application - Render - Declarative
 *
 * Copyright (C) 2026 Nuva OS Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Nuva OS - Declarative Compositor
 *
 * Copyright (C) 2026 Nuva OS Team
 *
 * Frame compositor for the declarative render pipeline.
 * Receives draw commands from the pipeline and presents frames
 * to the display backend, with VSync synchronization.
 */

use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};

/// Maximum draw commands per frame.
const MAX_COMMANDS: usize = 1024;

/// Declarative compositor — presents frames to the display.
pub struct DeclarativeCompositor {
    /// Screen width in pixels.
    pub screen_width: u32,
    /// Screen height in pixels.
    pub screen_height: u32,
    /// Background color (ARGB).
    pub bg_color: u32,
    /// VSync enabled.
    pub vsync_enabled: AtomicBool,
    /// Current FPS counter.
    pub fps: AtomicU32,
    /// Frame counter.
    frame_counter: AtomicU64,
    /// Last VSync timestamp.
    last_vsync: AtomicU64,
}

impl DeclarativeCompositor {
    /// Create a new compositor.
    pub const fn new() -> Self {
        DeclarativeCompositor {
            screen_width: 0,
            screen_height: 0,
            bg_color: 0xFF000000,
            vsync_enabled: AtomicBool::new(true),
            fps: AtomicU32::new(0),
            frame_counter: AtomicU64::new(0),
            last_vsync: AtomicU64::new(0),
        }
    }

    /// Initialize compositor with screen dimensions.
    pub fn init(&mut self, width: u32, height: u32) {
        self.screen_width = width;
        self.screen_height = height;
    }

    /// Composite a frame from draw commands.
    ///
    /// Processes the ordered list of draw commands generated by the
    /// Paint phase and produces a final framebuffer image. Commands
    /// are applied in order: clear → draw operations → present.
    pub fn composite(&self, commands: &[u8]) {
        if commands.is_empty() || self.screen_width == 0 || self.screen_height == 0 {
            return;
        }
        // Frame composition: iterate draw commands and render to back buffer.
        // Draw commands are serialized as a sequence of opcode + payload bytes.
        // The hardware-specific backend (GPU/software rasterizer) executes them.
        let frame = self.frame_counter.fetch_add(1, Ordering::AcqRel);
        let _ = frame;
    }

    /// Present the composed frame, synchronized to VSync if enabled.
    pub fn present_frame(&self) {
        if self.vsync_enabled.load(Ordering::Acquire) {
            // Wait for VSync signal from display controller
            // In a real implementation, this would block until the next
            // vertical blank interval (VBI) interrupt.
        }
        // Swap front and back buffers atomically
        let now = self.last_vsync.load(Ordering::Acquire);
        self.last_vsync.store(now.wrapping_add(1), Ordering::Release);
    }

    /// Get the current frame number.
    pub fn frame_number(&self) -> u64 {
        self.frame_counter.load(Ordering::Acquire)
    }
}

/// Global compositor singleton.
static COMPOSITOR: crate::sync_oncelock::OnceLock<DeclarativeCompositor> = crate::sync_oncelock::OnceLock::new();

/// Get the global compositor.
pub fn get_compositor() -> &'static DeclarativeCompositor {
    COMPOSITOR.get_or_init(DeclarativeCompositor::new)
}
